= Analytics using the Ruby SDK
:description: Parallel data management for complex queries over many records, using a familiar SQL-like syntax.
:page-topic-type: howto
:page-edition: Enterprise Edition:

[abstract]
{description}



For complex and long-running queries, involving large ad hoc join, set, aggregation, and grouping operations, Couchbase Data Platform offers the xref:6.5@server:analytics:introduction.adoc[Couchbase Analytics Service (CBAS)].
This is the analytic counterpart to our xref:n1ql-queries-with-sdk.adoc[operational data focussed Query Service].
The analytics service is available in Couchbase Data Platform 6.0 and later (developer preview in 5.5).


== Getting Started

After familiarizing yourself with our xref:6.5@server:analytics:primer-beer.adoc[introductory primer],
in particular creating a dataset and linking it to a bucket to shadow the operational data,
try Couchbase Analytics using the Ruby SDK.
Intentionally, the API for analytics is very similar to that of the query service.
In these examples we will be using an `airports` dataset created on the `travel-sample` bucket.

[source,ruby]
----
include::example$analytics.rb[tag=simple]
----


== Queries

A query can either be `simple` or be `parameterized`.
If parameters are used, they can either be `positional` or `named`:

.Positional parameters
[source,ruby]
----
include::example$analytics.rb[tag=positional]
----

.Named parameters
[source,ruby]
----
include::example$analytics.rb[tag=named]
----

NOTE: As timeouts are propagated to the server by the client, a timeout set on the client side may be used to stop the processing of a request, in order to save system resources.
// See example in the next section.


== Options

Additional parameters may be sent as part of the query.


.AnalyticsOptions
[options="header"]
[cols="29,71"]
|====
| Name       | Description
| `String #client_context_id` | Provides a custom client context ID for this query; default is a random UUID.
| `Boolean #priority` | Allows certain requests to have higher priority than others.
| `Boolean #readonly` | Allows explicitly marking a query as being read-only, and not mutating any documents on the server side.
| `Symbol #scan_consistency` | Specifies level of consistency for the query -- `:not_bounded`, `:request_plus`.
| `Integer #scan_wait` | The maximum duration (in milliseconds) the query engine is willing to wait before failing.
| `Integer #timeout` | Timeout in milliseconds.
| `JsonTranscoder #transcoder` | Transcoder to use on rows.
|====

Here, we set a `client_context_id`:

[source,ruby]
----
include::example$analytics.rb[tag=clientcontextid]
----

And here we set high priority for the query:

[source,ruby]
----
include::example$analytics.rb[tag=priority]
----

Here we pass `readonly` to explicitly mark a query as being read only, and not mutating any documents on the server side.

[source,ruby]
----
include::example$analytics.rb[tag=readonly]
----


== Handling the Response

The analytics query result may contain various sorts of data and metadata,
depending upon the nature of the query,
as you will have seen when working through our xref:6.5@server:analytics:primer-beer.adoc[introductory primer].

// Move these to Error reference doc?
// Common errors are listed in our xref:ref:error-codes.adoc#analytics-errors[Errors Reference doc], with
Errors caused by resource unavailability (such as timeouts and _Operation cannot be performed during rebalance_ messages) leading to an xref:howtos:error-handling.adoc#retry[automatic retry] by the SDK.

////
Moving these to error reference doc
----
21002: Request timed out and will be cancelled
23000: Analytics Service is temporarily unavailable
23003: Operation cannot be performed during rebalance
23007: Job queue is full with [string] jobs
----
////

=== MetaData

The `metadata` object contains useful metadata, such as `Metrics` and `ClientContextID`.

[source,ruby]
----
include::example$analytics.rb[tag=printmetrics]
----

// For a listing of available `Metrics` in `MetaData`, see the xref:concept-docs:analytics-for-sdk-users.adoc[Understanding Analytics] SDK doc.



== Scan Consistency


Like the xref:n1ql-queries-with-sdk.adoc#scan-consistency[Couchbase Query Service], and xref:full-text-searching-with-sdk.html#consistency[Search],
Analytics allows `:request_plus` queries -- ensuring results contain information from updated indexes:

[source,ruby]
----
include::example$analytics.rb[tag=scanconsistency]
----



== Scoped Queries on Named Collections

Given a dataset created against a collection, for example:

[source,n1ql]
----
CREATE DATASET `airports-collection` ON `travel-sample`.inventory.airport;
----

You can run a query as follows:

[source,ruby]
----
include::example$analytics.rb[tag=handle-collection]
----

In addition to running a query via the `Cluster` object, you can run one via the `Scope` object.

[source,ruby]
----
include::example$analytics.rb[tag=handle-scope]
----