= Handling Errors
:description: Error handling from the Ruby SDK.
:navtitle: Handling Errors
:page-topic-type: howto
:page-aliases: ROOT:handling-error-conditions,ROOT:exception-handling
:source-language: ruby

[abstract]
{description}


Errors are inevitable.
The developer’s job is to be prepared for whatever is likely to come up -- and to try and be prepared for anything that conceivably could come up.
Couchbase gives you a lot of flexibility, but it is recommended that you equip yourself with an understanding of the possibilities.


== How the SDK Handles Errors

Couchbase-specific exceptions are all derived from `Couchbase::Error::CouchbaseError`.
Errors that cannot be recovered by the SDK will be returned to the application.
These unrecoverable errors are left to the application developer to handle -- this section covers handling many of the common error scenarios.


== Handling Errors

The approach will depend upon the type of error thrown.
Is it transient?
Is it even recoverable?
Below we examine error handling strategies in relation to the Couchbase SDKs, then take a practical walk through some common error scenarios you are likely to have to handle when working with a Couchbase cluster.


=== Failing
While most of the time you want more sophisticated error handling strategies, sometimes you just need to fail.
It makes no sense for some errors to be retried, either because they are not transient, or because you already tried everything to make it work and it still keeps failing.
If containment is not able to handle the error, then it needs to propagate up to a parent component that can handle it.

For synchronous programs, every error is converted into an Exception and thrown so that you can use regular
`begin`/`rescue` semantics.

If you do not catch the Exception, it will bubble up:

[source,ruby]
----
Traceback (most recent call last):
	4: from examples/crud.rb:21:in `<main>'
	3: from lib/couchbase/cluster.rb:56:in `bucket'
	2: from lib/couchbase/cluster.rb:56:in `new'
	1: from lib/couchbase/bucket.rb:29:in `initialize'
lib/couchbase/bucket.rb:29:in `open_bucket': unable open bucket "travel-sample": bucket_not_found (Couchbase::Error::BucketNotFound)
----


=== Logging

It is always important to log errors, but even more so in the case of reactive applications. Because of the event driven
nature, stack traces get harder to look at, and caller context is sometimes lost.

Refer to the xref:collecting-information-and-logging.adoc[Logging page] for more details.


=== Retry

Transient errors -- such as those caused by resource starvation -- are best tackled with one of the following retry strategies:

* Retry immediately.
* Retry with a fixed delay.
* Retry with a linearly increasing delay.
* Retry with an exponentially increasing delay.
* Retry with a random delay.


////
[source,ruby]
----
include::example$error_handling.rb[tag=handle_retryable]
----
////

== KV

The KV Service exposes several common errors that can be encountered -- both during development, and to be handled by the production app. 
Here we will cover some of the most common errors.

=== Document does not exist

[source,ruby]
----
include::example$error_handling.rb[tag=DocumentNotFound]
----

=== Document already exists

[source,ruby]
----
include::example$error_handling.rb[tag=DocumentExists]
----

=== Document too large

`Couchbase::Error::ValueTooLarge`

=== CAS Mismatch

[source,ruby]
----
include::example$error_handling.rb[tag=CasMismatch]
----

=== Durability ambiguous

[source,ruby]
----
include::example$error_handling.rb[tag=DurabilityAmbiguous]
----

=== Durability invalid level

[source,ruby]
----
include::example$error_handling.rb[tag=DurabilityLevelNotAvailable]
----


== Query and Analytics Errors

N1QL and Analytics either return results or an error. 

////
If there is an error then it exposed in the following way(s):

== Search and View Errors

Unlike N1QL and Analytics, Search and Views can return multiple errors as well as errors and partial results.
// This next bit is going to be highly SDK specific too.

== Connections...
// Network / buckets / Timeouts / …

Networks, remotely-located clusters, and XDCR all offer opportunities for packets to go astray, or resources to go offline or become temporarily unavailable.
// As well as the above `Timeout` errors, and those in the next section on authenticating against clusters, there are ??network-related??
// The most common scenarios that the developer is likely to encounter when working with Couchbase Clusters are ?????

== Authentication

=== RBAC Roles - permissions on Service / Bucket / etc.

Standard since Couchbase Data Platform 5.0, xref:[Role Based Access Control (RBAC)] gives fine-grained permissions designed to protect the security of and access to data with a range of user roles encompassing different privileges.
xref:7.1@server:learn:security/authorization-overview.adoc[Refer to our Authorization pages] for a fuller understanding.

The developer must match an application’s need for data access with the necessary permissions for access.
// SCENARIO??
// ---> Certificates?

NOTE: If you are using Couchbase Community Edition, the only _roles_ available are xref:link-here[Bucket Full Access, Admin, and Read-only Admin].

== Additional Resources

Errors & Exception handling is an expansive topic.
Here, we have covered examples of the kinds of exception scenarios that you are most likely to face.
More fundamentally, you also need to weigh up xref:concept-docs:durability-replication-failure-considerations.adoc[concepts of durability].

Diagnostic methods are available to check on the xref:health-check.adoc[health if the cluster], and the xref:tracing-from-the-sdk.adoc[health of the network].

Logging methods are dependent upon the platform and SDK used.
We offer xref:collecting-information-and-logging.adoc[recommendations and practical examples].

We have a xref:ref:error-codes.adoc[listing of error messages], with some pointers to what to do when you encounter them.
////
