= Search
:description: You can use the Search Service to create queryable, search indexes in Couchbase Server.
:page-topic-type: howto
:page-toclevels: 2
:page-pagination: full

[abstract]
{description}


The Search Service -- or _Search_ for short -- allows you to create, manage, and query search indexes on JSON documents stored in Couchbase buckets. 
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.


There are two APIs for querying search: `cluster.searchQuery()`, and `cluster.search()`.
Both are also available at the Scope level.

The former API supports Search queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.



[TIP]
.Search Results Limit
====
By default, the Search Service returns only the first 10 matches (`size: 10`, `from: 0`).
To retrieve more results, you must explicitly define pagination settings such as `size` or `from` in your query.

For information about formatting your Search query and specifying limits, see xref:server:search:search-request-params.adoc[].

For information about pagination in Search responses, see xref:server:fts:fts-search-response.adoc#pagination[Pagination].
====


== Index Creation

For the purposes of the below examples we will use the Beer Sample sample bucket.
The Search indexes can be xref:{version-server}@server:fts:fts-creating-indexes.adoc[created through the UI or throuth the REST API], or created programatically as follows:

[source,ruby]
----
include::example$search.rb[tag=index]
----


== Examples

In versions of Couchbase Server starting from 7.6, Search queries are executed at either the Scope or the Cluster level;
in earlier versions, they are just performed at the cluster level. (not bucket or collection). 

We will perform an Search query here - see the <<vector search>> section for examples of that.
Here is a simple query that looks for the text "hop beer" using the defined index:

[source,ruby]
----
include::example$search.rb[tag=simple]
----

`match_phrase()` builds a phrase query is built from the results of an analysis of the terms in the query phrase; 
here it's built on a search in the name field.

[source,ruby]
----
include::example$search.rb[tag=query_fields]
----


== Working with Results

The result of a Search query has three components: rows, facets, and metdata.  
Rows are the documents that match the query.  
Facets allow the aggregation of information collected on a particular result set.  
Metdata holds additional information not directly related to your query, such as success, total hits, and how long the query took to execute in the cluster.

.Iterating Rows
Here we are iterating over the rows that were returned in the results.
Highlighting has been selected for the description field in each row, 
and the total number of rows is taken from the `metrics` returned in the metadata:

[source,ruby]
----
include::example$search.rb[tag=highlight]
----

With `skip` and `limit` a slice of the returned data may be selected:

[source,ruby]
----
include::example$search.rb[tag=limit]
----

Ordering rules can be applied via `sort` and `SearchSort`:

[source,ruby]
----
include::example$search.rb[tag=sort]
----

.Facets
[source,ruby]
----
include::example$search.rb[tag=facet,]
----

== Scoped vs Global Indexes

The Search APIs exist at both the `Cluster` and `Scope` levels.

This is because the Search Service supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.search()` for scoped indexes.



[source,ruby]
----
include::example$search.rb[tag=fts-search-request, indent=0]
----
The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the xref:n1ql-queries-with-sdk.adoc#scan-consistency[Couchbase Query Service], the Search Service allows `consistent_with()` queries -- _Read-Your-Own_Writes (RYOW)_ consistency,
ensuring results contain information from updated indexes:

[source,ruby]
----
include::example$search.rb[tag=consistency]
----
