= Full Text Search from the SDK
:description: You can use the Full Text Search service (FTS) to create queryable, full-text indexes in Couchbase Server.
:navtitle: Search from the Ruby SDK
:page-topic-type: howto

[abstract]
{description}


Full Text Search (FTS) -- or _Search_ for short -- allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase buckets. 
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.

The Ruby SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying REST API.

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `bucket = cluster.bucket("bucket-name")` before you can use Search.


== Index Creation

For the purposes of the below examples we will use the Beer Sample sample bucket.
Full Text Search indexes can be xref:6.5@server:fts:fts-creating-indexes.adoc[created through the UI or throuth the REST API], or created programatically as follows:

[source,ruby]
----
include::example$search.rb[tag=index]
----


== Examples

Search queries are executed at Cluster level (not bucket or collection). 
As of Couchbase Server 6.5+ they do also not require a bucket to be opened first.  
In older versions of Couchbase Server, even though executed at Cluster level, a bucket must be opened before performing queries.

Here is a simple query that looks for the text "hop beer" using the defined index:

[source,ruby]
----
include::example$search.rb[tag=simple]
----

`match_phrase()` builds a phrase query is built from the results of an analysis of the terms in the query phrase; 
here it's built on a search in the name field.

[source,ruby]
----
include::example$search.rb[tag=query_fields]
----


== Working with Results

The result of a Search query has three components: rows, facets, and metdata.  
Rows are the documents that match the query.  
Facets allow the aggregation of information collected on a particular result set.  
Metdata holds additional information not directly related to your query, such as success, total hits, and how long the query took to execute in the cluster.

.Iterating Rows
Here we are iterating over the rows that were returned in the results.
Highlighting has been selected for the description field in each row, 
and the total number of rows is taken from the `metrics` returned in the metadata:

[source,ruby]
----
include::example$search.rb[tag=highlight]
----

With `skip` and `limit` a slice of the returned data may be selected:

[source,ruby]
----
include::example$search.rb[tag=limit]
----

Ordering rules can be applied via `sort` and `SearchSort`:

[source,ruby]
----
include::example$search.rb[tag=sort]
----

.Facets
[source,ruby]
----
include::example$search.rb[tag=facet,]
----


== Consistency

Like the xref:n1ql-queries-with-sdk.adoc#scan-consistency[Couchbase Query Service], FTS allows `consistent_with()` queries -- _Read-Your-Own_Writes (RYOW)_ consistency,
ensuring results contain information from updated indexes:

[source,ruby]
----
include::example$search.rb[tag=consistency]
----
