= Search
:description: You can use the Full Text Search service (FTS) to create queryable, full-text indexes in Couchbase Server.
:page-topic-type: howto
:page-toclevels: 2
:page-pagination: full

[abstract]
{description}


Full Text Search (FTS) -- or _Search_ for short -- allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase buckets. 
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.


There are two APIs for querying search: `cluster.searchQuery()`, and `cluster.search()`.
Both are also available at the Scope level.

The former API supports FTS queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.



== Index Creation

For the purposes of the below examples we will use the Beer Sample sample bucket.
Full Text Search indexes can be xref:7.1@server:fts:fts-creating-indexes.adoc[created through the UI or throuth the REST API], or created programatically as follows:

[source,ruby]
----
include::example$search.rb[tag=index]
----


== Examples

In versions of Couchbase Server starting from 7.6, Search queries are executed at either the Scope or the Cluster level;
in earlier versions, they are just performed at the cluster level. (not bucket or collection). 

We will perform an FTS query here - see the <<vector search>> section for examples of that.
Here is a simple query that looks for the text "hop beer" using the defined index:

[source,ruby]
----
include::example$search.rb[tag=simple]
----

`match_phrase()` builds a phrase query is built from the results of an analysis of the terms in the query phrase; 
here it's built on a search in the name field.

[source,ruby]
----
include::example$search.rb[tag=query_fields]
----


== Working with Results

The result of a Search query has three components: rows, facets, and metdata.  
Rows are the documents that match the query.  
Facets allow the aggregation of information collected on a particular result set.  
Metdata holds additional information not directly related to your query, such as success, total hits, and how long the query took to execute in the cluster.

.Iterating Rows
Here we are iterating over the rows that were returned in the results.
Highlighting has been selected for the description field in each row, 
and the total number of rows is taken from the `metrics` returned in the metadata:

[source,ruby]
----
include::example$search.rb[tag=highlight]
----

With `skip` and `limit` a slice of the returned data may be selected:

[source,ruby]
----
include::example$search.rb[tag=limit]
----

Ordering rules can be applied via `sort` and `SearchSort`:

[source,ruby]
----
include::example$search.rb[tag=sort]
----

.Facets
[source,ruby]
----
include::example$search.rb[tag=facet,]
----



== Scoped vs Global Indexes
The FTS APIs exist at both the `Cluster` and `Scope` levels.

This is because FTS supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.searchQuery()` / `Scope.search()` for scoped indexes.

== Vector Search
As of Couchbase Server 7.6, the FTS service supports vector search in additional to traditional full text search queries.
// todo link to the server docs when available

=== Examples
==== Single vector query
In this first example we are performing a single vector query:
[source,java]
----
SearchRequest request = SearchRequest
        .create(VectorSearch.create(VectorQuery.create("vector_field", vectorQuery)));

SearchResult result = scope.search("travel-sample-index", request);
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional FTS query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `float[]`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the FTS index "travel-sample-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.search()`.
If it was a global index we would use `cluster.search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

==== Multiple vector queries
You can run multiple vector queries together:

[source,java]
----
SearchRequest request = SearchRequest
        .create(VectorSearch.create(List.of(
                        VectorQuery.create("vector_field", vectorQuery).numCandidates(2).boost(0.3),
                        VectorQuery.create("vector_field", anotherVectorQuery).numCandidates(5).boost(0.7)));

SearchResult result = scope.search("travel-sample-index", request);
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.

==== Combining FTS and vector queries
You can combine a traditional FTS query with vector queries:

[source,java]
----
SearchRequest request = SearchRequest.create(SearchQuery.matchAll())
        .vectorSearch(VectorSearch.create(VectorQuery.create("vector_field", vectorQuery)));

SearchResult result = scope.search("travel-sample-index", request);
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.

==== FTS queries
And note that traditional FTS queries, without vector search, are also supported with the new `cluster.search()` / `scope.search()` APIs:

[source,java]
----
SearchRequest request = SearchRequest.create(SearchQuery.matchAll());

SearchResult result = scope.search("travel-sample-index", request);
----

The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the xref:n1ql-queries-with-sdk.adoc#scan-consistency[Couchbase Query Service], FTS allows `consistent_with()` queries -- _Read-Your-Own_Writes (RYOW)_ consistency,
ensuring results contain information from updated indexes:

[source,ruby]
----
include::example$search.rb[tag=consistency]
----
