= Data Operations
:description: Data service offers the simplest way to retrieve or mutate data where the key is known.
:page-topic-type: howto
:page-aliases: document-operations.adoc
:page-toclevels: 2
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Here we cover CRUD operations, document expiration, and optimistic locking with CAS.


////
The complete code sample used on this page can be downloaded from
//  xref::example$document.cs[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.
////

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Ruby SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation, with simple error handling:

[source,ruby]
----
include::example$kv_operations.rb[tag=insert]
----


Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

// _Timeout_ is an optional parameter which is a integer value representing time duration in microseconds..
// Timeout sets the timeout value for the underlying network connection.
// We will add to these options for the _Replace_ example:

[source,ruby]
----
include::example$kv_operations.rb[tag=replace]
----

// The example above also shows how to handle the case when optimistic falure will fail.

Expiration sets an explicit time to live (TTL) for a document.
// We'll discuss modifying `expiry` in more details xref:#php-modifying-expiration[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the
xref:7.1@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,ruby]
----
include::example$kv_operations.rb[tag=expiry-insert]
----

== Durability

Writes in Couchbase are written to a single node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.

The optional `durability_level` parameter, which all mutating operations accept, allows the application to wait until this replication (or persistence) is successful before proceeding.

It can be used like this:

[source,ruby]
----
include::example$kv_operations.rb[tag=durability,indent=0]
----

If no argument is provided the application will report success back as soon as the primary node has acknowledged the mutation in its memory.
However, we recognize that there are times when the application needs that extra certainty that especially vital mutations have been successfully replicated,
and the other durability options provide the means to achieve this.

The options differ depending on what Couchbase Server version is in use.
If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature,
in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved.
The three replication levels are:

* `:majority` - The server will ensure that the change is available in memory on the majority of configured replicas.
* `:majority_and_persist_to_active` - Majority level, plus persisted to disk on the active node.
* `:persist_to_majority` - Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of safety.
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

If a version of Couchbase Server earlier than 6.5 is being used then the application can fall-back to xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability].
Here the SDK will do a simple poll of the replicas and only return once the requested durability level is achieved.
This can be achieved like this:

[source,ruby]
----
include::example$kv_operations.rb[tag=durability-observed,indent=0]
----

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration,
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Document Operations].
====

== Retrieving full documents

Using the `.get()` method with the document key can be done in a similar fashion to the other operations:

[source,ruby]
----
include::example$kv_operations.rb[tag=get-simple]
----

You can then add in logic to filter on the fields returned:

[source,ruby]
----
include::example$kv_operations.rb[tag=get]
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:


[source,ruby]
----
include::example$kv_operations.rb[tag=remove]
----

// TODO: old-style durability will come later


== Expiration / TTL


Couchbase Server includes an option to have particular documents automatically expire after a set time.
This can be useful for some use-cases, such as user sessions, caches, or other temporary documents.

You can set an expiry value when creating a document:


[source,ruby]
----
include::example$kv_operations.rb[tag=expiry-insert]
----

When getting a document, the expiry is not provided automatically by Couchbase Server but it can be requested:

[source,ruby]
----
include::example$kv_operations.rb[tag=expiry-get]
----


NOTE: The type returned by `#expiry_time` is `Time`, and always represents absolute time when the document will expire. 
The `#expiry` method that returned integer number of seconds since epoch is _*deprecated*_, and will be removed in release `3.1`.


Note that when updating the document, special care must be taken to avoid resetting the expiry to zero.
Here's how:


[source,ruby]
----
include::example$kv_operations.rb[tag=expiry-replace]
----

Some applications may find `getAndTouch` useful, which fetches a document while updating its expiry field.
It can be used like this:


[source,ruby]
----
include::example$kv_operations.rb[tag=expiry-touch]
----


include::{version-common}@sdk:shared:partial$documents.adoc[tag=exp-note]


== Atomic Counters

The value of a document can be increased or decreased atomically using `#increment()` and `#decrement()` on the `Couchbase::BinaryCollection`.
See the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/BinaryCollection.html[API Guide] for more information.

.Increment
[source,ruby]
----
include::example$kv_counter.rb[tag=increment]
----

[source,ruby]
----
include::example$kv_counter.rb[tag=incrementwithoptions]
----

.Decrement
[source,ruby]
----
include::example$kv_counter.rb[tag=decrement]
----

.Decrement (with options)
[source,ruby]
----
include::example$kv_counter.rb[tag=decrementwithoptions]
----

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change


include::7.1@sdk:shared:partial$atomic.adoc[tag=xdcr]


== Scoped KV Operations

It is possible to perform scoped key-value operations on named xref:{version-server}@server:learn:data/scopes-and-collections.adoc[`Collections`] _with Couchbase Server release 7.x_.
See the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Collection.html[API docs] for more information.

Here is an example showing an upsert in the `users` collection, which lives in the `travel-sample.tenant_agent_00` keyspace:

[source,ruby]
----
include::example$kv_operations.rb[tag=named-collection-upsert]
----

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

// For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
