= N1QL Queries from the SDK
:navtitle: N1QL from the SDK
:page-topic-type: howto
:page-aliases: n1ql-query

[abstract]
You can query for documents in Couchbase using the N1QL query language, a language based on SQL, but designed for structured and flexible JSON documents.
Querying can solve typical programming tasks such as finding a user profile by email address, facebook login, or user ID.



Our query service uses N1QL, which will be fairly familiar to anyone who's used any dialect of SQL.
xref:#additional_resources[Further resources] for learning about N1QL are listed at the bottom of the page.
Before you get started you may wish to checkout the xref:6.5@server:n1ql:n1ql-language-reference/index.adoc[N1QL intro page], or just dive in with a query against our travel sample data set.
In this case, the one thing that you need to know is that in order to make a Bucket queryable, it must have at least one index defined.
You can define a _primary_ index on a bucket.
When a primary index is defined you can issue non-covered queries on the bucket as well.

Use
xref:6.5@server::tools/cbq-shell.html[cbq], our interactive Query shell.
Open it, and enter the following:

[source,n1ql]
----
CREATE PRIMARY INDEX ON `travel-sample`
----

or replace _travel-sample_ with a different Bucket name to build an index on a different dataset.

NOTE: The default installation places cbq in `/opt/couchbase/bin/` on Linux, `/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/cbq` on OS X, and `C:\Program Files\Couchbase\Server\bin\cbq.exe` on Microsoft Windows.


== A Simple Query

Here’s the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,ruby]
----
include::example$queries.rb[tag=simple]
----

A query is always performed at the `Cluster` level, using the `query()` method.
It takes the statement as a required argument and then allows additional options if needed.

A complete list of `QueryOptions` can be found in the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Cluster/QueryOptions.html[API docs].
Here we pass `readonly` to explicitly mark a query as being read only, and not mutating any documents on the server side.

[source,ruby]
----
include::example$queries.rb[tag=read-only]
----


== Queries & Placeholders

Placeholders allow you to specify variable constraints for an otherwise constant query.
There are two variants of placeholders: _postional_ and _named_ parameters.
Positional parameters use an ordinal placeholder for substitution and named parameters use variables.
A named or positional parameter is a placeholder for a value in the WHERE, LIMIT or OFFSET clause of a query.
Note that both parameters and options are optional.

.Positional parameter example:
[source,ruby]
----
include::example$queries.rb[tag=positional]
----

.Named parameter example:
[source,ruby]
----
include::example$queries.rb[tag=named]
----


== The Query Result

When performing a query, the response you receive is a `QueryResult`.
If no exception gets raised the request succeeded and provides access to both the rows returned and also associated `QueryMetaData`.

[source,ruby]
----
include::example$queries.rb[tag=client-context-id]
----

The `QueryMetaData` provides insight into some basic profiling/timing information as well as information like the `clientContextId`.

.QueryMetaData
[options="header"]
[cols="33,67"]
|====
| Name       | Description
| `String #request_Id` | Returns the request identifer string of the query request.
| `String #client_context_id` | Returns the context ID either generated by the SDK or supplied by the user.
| `Symbol #status` | Returns raw query execution status as returned by the query engine.
| `QueryMetrics #metrics` | Metrics as returned by the query engine, if enabled.
| `Hash #signature` | Returns the signature as returned by the query engine which is then decoded as JSON object.
| `List<QueryWarning> #warnings` | Non-fatal errors are available to consume as warnings on this method.
| `Hash #profile` | If enabled returns additional profiling information of the query.
|====

For example, here is how you can print the `executionTime` of a query:

[source,ruby]
----
include::example$queries.rb[tag=print-metrics]
----


== Scan Consistency


Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.

* A N1QL query using the default *Not Bounded* Scan Consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

* With Scan Consistency set to *request_plus*, all document changes and index updates are processed before the query is run.
Select this when consistency is always more important than performance.

* For a middle ground, *AtPlus* is a "read your own write" (RYOW) option, which means it just waits for the new documents that you specify to be indexed, rather than an entire index of multiple documents.
// See the xref:scan-consistency-examples.adoc[examples] for how to use *AtPlus* for the best performance balance for many circumstances.

.ScanConsisteny (request_plus)

[source,ruby]
----
include::example$queries.rb[tag=scan-consistency]
----


== Querying at Scope level

From version 3.0.2 of the Ruby SDK, it is possible to query off the xref:7.0@server:learn:data/scopes-and-collections.adoc[`Scope` level] _with the beta version of the next Couchbase Server release, 7.0β_,
using the `query()` method.
It takes the statement as a required argument, and then allows additional options if needed.

CAUTION: This feature is marked xref:project-docs:compatibility.adoc#interface-stability[_Uncommitted_].
Expect a promotion to _Committed_ API in the next minor release (3.1).

The code snippet below shows how to run a simple query to fetch 10 random rows from travel-sample and print the results, 
the assumption is that the `airline` collection exists within a scope `us`.

[source,ruby]
----
include::example$queries.rb[tag=scope]
----

A complete list of `QueryOptions` can be found in the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Options/Query.html[API docs].


== Additional Resources

NOTE: N1QL is not the only query option in Couchbase.
Be sure to check that your xref:concept-docs:data-services.adoc#use-cases[use case] fits your selection of query service.

For a deeper dive into N1QL from the SDK, refer to our xref:concept-docs:n1ql-query.adoc[N1QL SDK concept doc].

The xref:6.5@server:n1ql:n1ql-language-reference/index.adoc[Server doc N1QL intro] introduces up a complete guide to the N1QL language, including all of the latest additions.

The http://query.pub.couchbase.com/tutorial/#1[N1QL interactive tutorial] is a good introduction to the basics of N1QL use.

// Indexes / GSI links?

// SQL++ / Analytics.
