= Provisioning Cluster Resources
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

[abstract]
Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
Common use cases are outlined here, more recherché use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management.html[API docs].

include::6.6@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Ruby SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* BucketManager -- `Couchbase::Management::BucketManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[API docs].
* UserManager -- `Couchbase::Management::UserManager`  
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/UserManager.html[API docs].
* QueryIndexManager -- `Couchbase::Management::QueryIndexManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/QueryIndexManager.html[API docs].
* AnalyticsIndexManager -- `Couchbase::Management::AnalyticsIndexManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/AnalyticsIndexManager.html[API docs].
* SearchIndexManager -- `Couchbase::Management::SearchIndexManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/SearchIndexManager.html[API docs].
* CollectionManager -- `Couchbase::Management::CollectionManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[API docs].
* ViewIndexManager -- `Couchbase::Management::ViewIndexManager` 
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/ViewIndexManager.html[API docs].

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.Bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[BucketManager] interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `#create_bucket()` method.

include::6.6@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

////
Here is the list of parameters available:
// Ruby SDK doesn't have a good equivalent list...
|====
| Name | Description | Can be updated
| `Name string` | The name of the bucket, required for creation. | false
| `FlushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<go-flushing>> section below). | true
| `ReplicaIndexDisabled boolean` | Whether or not to replicate indexes. | false
| `RAMQuotaMB uint64` | How much memory should each node use for the bucket, required for creation. | true
| `NumReplicas uint32` | The number of replicas to use for the bucket. | true
| `BucketType BucketType` | The type of the bucket, required for creation. | false
| `EvictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `MaxTTL time.Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `CompressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `ConflictResolutionType ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `seqno` | false
|====
////
The following example creates a new bucket, adding settings including making it flushable:

[source,ruby]
----
include::example$provisioning-resources-buckets.rb[tag=create]
----

We can retrieve information on various settings:

[source,ruby]
----
include::example$provisioning-resources-buckets.rb[tag=get]
----

As well as flushing the bucket.


== Flushing Buckets

include::6.6@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `flush_bucket()` method.


[source,ruby]
----
flush_bucket(bucket_name, options = FlushBucketOptions.new)
----

The `flush_bucket()` operation may fail if the bucket does not have flush enabled, in which case it will return an `Error::BucketNotFlushable`.


== Collection Management

This is a xref:6.@server:developer-preview:collections/collections-overview.adoc[Developer Preview feature], see the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[API doc].

There is a full example in the https://github.com/couchbase/couchbase-ruby-client/blob/master/examples/managing_collections.rb[Ruby SDK repo on GitHub].


== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs, linked xref:#further-reading-api-guides[below].


== View Management

include::6.6@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on the `ViewIndexManager` instance:


[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=viewmgr]
----

The following example upserts a design document with two views:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=createView]
----

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespaceDevelopment`, the other option is `DesignDocumentNamespaceProduction`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=getView]
----

We've created the design document using `DesignDocumentNamespaceDevelopment` and now want to push it to production, we can do this with:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=publishView]
----

To remove this design document:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=removeView]
----



== Further Reading & API Guides

The https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management.html[API Guide] contains info on the following Management APIs:

* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[BucketManager] -- `Couchbase::Management::BucketManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/UserManager.html[UserManager] -- `Couchbase::Management::UserManager` 
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/QueryIndexManager.html[QueryIndexManager] -- `Couchbase::Management::QueryIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/AnalyticsIndexManager.html[AnalyticsIndexManager] -- `Couchbase::Management::AnalyticsIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/SearchIndexManager.html[SearchIndexManager] -- `Couchbase::Management::SearchIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[CollectionManager] -- `Couchbase::Management::CollectionManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/ViewIndexManager.html[ViewIndexManager] -- `Couchbase::Management::ViewIndexManager`.
