= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management.html[API docs].

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Ruby SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* BucketManager -- `Couchbase::Management::BucketManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[API docs].
* UserManager -- `Couchbase::Management::UserManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/UserManager.html[API docs].
* QueryIndexManager -- `Couchbase::Management::QueryIndexManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/QueryIndexManager.html[API docs].
* AnalyticsIndexManager -- `Couchbase::Management::AnalyticsIndexManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/AnalyticsIndexManager.html[API docs].
* SearchIndexManager -- `Couchbase::Management::SearchIndexManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/SearchIndexManager.html[API docs].
* CollectionManager -- `Couchbase::Management::CollectionManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[API docs].
* ViewIndexManager -- `Couchbase::Management::ViewIndexManager`
-- see https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/ViewIndexManager.html[API docs].

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.Bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[BucketManager] interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `#create_bucket()` method.

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

See the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketSettings.html[API docs^] for a full list of settings options.


The following example creates a new bucket, adding settings including making it flushable:

[source,ruby]
----
include::example$provisioning-resources-buckets.rb[tag=create]
----

We can retrieve information on various settings:

[source,ruby]
----
include::example$provisioning-resources-buckets.rb[tag=get]
----

As well as flushing the bucket.


== Flushing Buckets

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `flush_bucket()` method.


[source,ruby]
----
flush_bucket(bucket_name, options = FlushBucketOptions.new)
----

The `flush_bucket()` operation may fail if the bucket does not have flush enabled, in which case it will return an `Error::BucketNotFlushable`.


== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[`CollectionManager` API documentation]
for further details.

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=create-collection-manager,indent=0]
----

=== Creating and Deleting Scopes and Collections

You can create a scope:

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=drop-collection,indent=0]

include::example$provisioning-resources-collections.rb[tag=drop-scope,indent=0]

----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with
xref:server:learn:security/roles.adoc#data-reader[Data Reader]

You can create users with the appropriate RBAC programmatically:

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=scopeAdmin, indent=0]

----

=== Listing the Scopes and Collections available

You can enumerate Scopes and Collections using
the `CollectionManager.get_all_scopes()` method and
the `Scope.collections` property.

[source,ruby]
----
include::example$provisioning-resources-collections.rb[tag=listing-scope-collection, indent=0]
----

=== More examples

There is a full example in the https://github.com/couchbase/couchbase-ruby-client/blob/master/examples/managing_collections.rb[Ruby SDK repo on GitHub].


== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs, linked xref:#further-reading-api-guides[below].


== View Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` classes.
All operations on design documents are performed on the `ViewIndexManager` instance:

There is a full example in the https://github.com/couchbase/couchbase-ruby-client/blob/master/examples/managing_view_indexes.rb[Ruby SDK repo on GitHub].


== Further Reading & API Guides

The https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management.html[API Guide] contains info on the following Management APIs:

* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/BucketManager.html[BucketManager] -- `Couchbase::Management::BucketManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/UserManager.html[UserManager] -- `Couchbase::Management::UserManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/QueryIndexManager.html[QueryIndexManager] -- `Couchbase::Management::QueryIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/AnalyticsIndexManager.html[AnalyticsIndexManager] -- `Couchbase::Management::AnalyticsIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/SearchIndexManager.html[SearchIndexManager] -- `Couchbase::Management::SearchIndexManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/CollectionManager.html[CollectionManager] -- `Couchbase::Management::CollectionManager`
* https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/Management/ViewIndexManager.html[ViewIndexManager] -- `Couchbase::Management::ViewIndexManager`.
