= Authenticating against Couchbase Server
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

[abstract]
As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,ruby]
----
include::hello-world:example$start_using.rb[tag=connect,indent=0]
----


include::6.5@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::6.5@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating a Ruby Client by Certificate

For sample procedures whereby certificates can be generated and deployed, see xref:6.5@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed:


// include::example$auth.rb[tag=auth1,indent=0]

[source,ruby]
----
include::example$auth.rb[tag=auth2,indent=0]
----


include::6.5@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,ruby]
----
include::example$auth.rb[tag=auth3,indent=0]
----
