= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:


[abstract]
{description}


The Couchbase Ruby SDK supports MRI Ruby versions 3.1, 3.2, and 3.3
 -- see the table below for <<ruby-version-compatibility,supported versions and dates>>.
// We follow list of supported versions at https://www.ruby-lang.org/en/downloads/branches/

== Platform Compatibility



=== Ruby Version Compatibility

The Couchbase Ruby SDK aims to support https://www.ruby-lang.org/en/downloads/branches/[all supported versions] of Ruby.
The table below indicates the Ruby SDK version where support of a version of Ruby was added.
Ruby versions that have reached their https://www.ruby-lang.org/en/downloads/branches/[End-of-Life date] are not supported.

.Supported Ruby Versions
[cols="5,8,8"]
|===
| Ruby Version | Support EOL | Couchbase SDK Versions Supported

| 3.1
| until 2025-03-31
| from 3.3.0

| 3.2
| until 2026-03-31
| from 3.4.0

| 3.3
| until 2026-03-31 (expected, TBC)
| from 3.5.0

|===


=== OS Compatibility

In general, the SDK can be expected to run on all of the Operating Systems supported by xref:{version-server}@server:install:install-platforms.adoc[Couchbase Server].

However, the {name-sdk} is tested and supported specifically on the following OSs and platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8 & 9;
* Oracle Linux 8 & 9.
* Ubuntu (LTS) 20.04 (_Focal_) & 22.04 (_Jammy_).
* Debian 10 (_Buster_), 11 (_Bullseye_), and Debian 12 (_Bookworm_).
* SUSE Enterprise Linux 12 & 15.
* Alpine Linux 3.18.

[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019 & 2022.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (March 2024): 14 (Sonoma), 13 (Ventura), and 12 (Monterey).
M1 ARM  architecture is fully supported in the Ruby SDK.

[discrete]
=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04+ (from SDK 3.4).
****


// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]



== Couchbase Server Compatibility

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.


=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the Ruby SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 3.2 - 3.4 | 3.5 - 3.6

| *Server 7.0 - 7.2*
| *✔*
| *✔*

| *Server 7.6*
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


=== Capella Compatibility

The Couchbase Ruby SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.0 & 7.1 | Server 7.2 | Server 7.6

| Enhanced Durability
3+| All SDK versions

| Durable Writes
3+| Since 3.0

| Analytics
3+| Since 2.6

| Collections
3+| Since 3.0.3

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
3+| Since SDK 3.2.0

| Request Tracing
3+| Since SDK 3.2.0

| Distributed ACID Transactions
3+| Not Yet Supported

| Cloud Native Gateway
3+| Not Yet Supported

| Vector Search
2+| N/A
| From SDK 3.5.0
|===





=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]




== SDK API Stability


include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]



