= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Ruby SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

[abstract]
{description}

The Couchbase Ruby SDK supports MRI Ruby versions 2.7, 3.0 and 3.1.
// We follow list of supported versions at https://www.ruby-lang.org/en/downloads/branches/


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Ruby SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25, 20, 20"]
|===
|  | SDK 3.0, 3.1 | SDK 3.2 | SDK 3.3

| *Server 6.0*
| *✔*
| *✔*
| *◎*

| *Server 6.5-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0-7.1*
| ◎
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 3.3 Ruby SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the 3.3 SDK includes the Capella client certificate ready installed.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,5,6,5"]
|===
| | Server 6.0 | Server 6.5 & 6.6 | Server 7.0 & 7.1

| Enhanced Durability
3+| All SDK versions

| Durable Writes
| Not Supported
2+| Since 3.0

| Analytics
3+| Since 3.0

| Default Collections
2+| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since 3.0.3

| Scope-Level N1QL Queries & all Collections features
3+| Not Supported
| Since SDK 3.2.0

| Request Tracing
2+| Not Supported
2+| Since SDK 3.2.0
|===

include::7.1@sdk:shared:partial$network-requirements.adoc[]


include::7.1@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::7.1@sdk:shared:partial$api-version.adoc[tag=api-version]

include::7.1@sdk:shared:partial$archive.adoc[tag=link]
