= Compatibility
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Ruby SDK supports MRI Ruby versions 3.0, 3.1, and 3.2
 -- see the table below for <<ruby-version-compatibility,supported versions and dates>>.
// We follow list of supported versions at https://www.ruby-lang.org/en/downloads/branches/


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Ruby SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25, 20, 20"]
|===
|  | SDK 3.0, 3.1 | SDK 3.2 | SDK 3.3, 3.4

| *Server 6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0-7.2*
| ◎
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Ruby SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]



== Ruby Version Compatibility

The Couchbase Ruby SDK aims to support https://www.ruby-lang.org/en/downloads/branches/[all supported versions] of Ruby.
The table below indicates the Ruby SDK version where support of a version of Ruby was added.
Ruby versions that have reached their https://www.ruby-lang.org/en/downloads/branches/[End-of-Life date] are not supported.

.Supported Ruby Versions
[cols="5,8,8"]
|===
| Ruby Version | Support EOL | Couchbase SDK Versions Supported

| 3.0
| until 2024-03-31
| from 3.1.0

| 3.1
| until 2025-03-31
| from 3.3.0

| 3.2
| until 2026-03-31
| from 3.4.0

|===



// TODO: Verify this with dev team (this has been copied over from Python, so best to double check that it is correct).
== Platform Compatibility

The Ruby SDK is built on top of the C++ SDK (not currently available separately), which is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8 -- but see note below;
* CentOS 7 & 8 -- but see note below.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (October 2022): 13 (Ventura), 12 (Monterey), and 11 (Big Sur).
M1 ARM architecture is fully supported.
****

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 3.4).


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,5"]
|===
| | Server 6.6 | Server 7.0 & 7.1

| Enhanced Durability
2+| All SDK versions

| Durable Writes
2+| Since 3.0

| Analytics
2+| Since 3.0

| Collections
| Developer Preview in 6.6, SDK 3.0
| Since 3.0.3

| Scope-Level {sqlpp} Queries & all Collections features
| Not Supported
| Since SDK 3.2.0

| Request Tracing
2+| Since SDK 3.2.0
|===

include::{version-common}@sdk:shared:partial$network-requirements.adoc[]


include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
