= Couchbase Ruby Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-ruby-sdk,ROOT:release-notes,ROOT:sdk-release-notes


[abstract]
Release notes, installation instructions, and download archive for the Couchbase Ruby Client.

These pages cover the 3.1 versions of the Couchbase Ruby SDK.

== SDK Installation

Ruby SDK supports MRI Ruby versions 2.5, 2.6, 2.7 and 3.0.
The source package is available through https://rubygems.org/gems/couchbase and can be installed with

[source,console]
----
gem install couchbase
----

Note that `--pre` is necessary when the SDK in Beta/Preview phase -- `gem install --pre couchbase` -- otherwise the latest stable release will be installed.

In addition to rubygems.org, we also maintain official gem repositories, where we publish not only source version of the
package, but also precompiled binaries for Linux and MacOS.

[cols="4,17"]
|===
| Ruby ABI version | Source URL
| 3.0   | https://packages.couchbase.com/clients/ruby/3.0.0/
| 2.7   | https://packages.couchbase.com/clients/ruby/2.7.0/
| 2.6   | https://packages.couchbase.com/clients/ruby/2.6.0/
| 2.5   | https://packages.couchbase.com/clients/ruby/2.5.0/
|===

To use official repository, it have to be registered in the `.gemrc` file:

The example above selects repository with the packages for Ruby 2.7.x. For other version, please refer the table.

The repository could be also specified in `Gemfile` for bundler. And in this case the source would be applied only for
Couchbase SDK library:

[source,ruby]
----
gem "couchbase", "3.1.0", :source => "https://packages.couchbase.com/clients/ruby/2.7.0/"
----

Or run in terminal:

[source,bash]
----
gem install couchbase --source https://packages.couchbase.com/clients/ruby/2.7.0/
----

And finally, it is possible to download the package and install from the file. In the notes below, we specify tables
with links to every release package along with precompiled binaries.

[source,bash]
----
wget https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-linux-2.7.0.gem
gem install couchbase-3.1.0-x86_64-linux-2.7.0.gem
----


[#latest-release]
== Version 3.1.0 (24 March 2021)

This is the first GA release of 3.1 series.

https://docs.couchbase.com/sdk-api/couchbase-ruby-client-3.1.0/index.html[API Reference]

* https://issues.couchbase.com/browse/RCBC-314[RCBC-314]:
  Fix class resolution for Analytics on scope level.

* https://issues.couchbase.com/browse/RCBC-276[RCBC-276]:
  Mark `create_as_deleted` of subdocument API as private.

* https://issues.couchbase.com/browse/RCBC-287[RCBC-287]:
  Update URLs of endpoints for Collections management API.

* https://issues.couchbase.com/browse/RCBC-303[RCBC-303]:
  Deprecate `CollectionManager#get_scope`, instead the application should use `CollectionManager#get_scopes` and
iterate/filter the results.

* https://issues.couchbase.com/browse/RCBC-313[RCBC-313]:
  Send collection name as value on network level for `0xbb` (`GET_COLLECTION_ID`) command.

* https://issues.couchbase.com/browse/RCBC-302[RCBC-302]:
  Allow to disable configuration push from server (using `enable_clustermap_notification=false` in the connection string).

* https://issues.couchbase.com/browse/RCBC-307[RCBC-307]:
  Allow to disable unordered execution of commands (using `enable_unordered_execution=false` in the connection string).

* The library does not keep GVL lock durng IO anymore. It release lock when scheduling command, and acquire it back once command is completed. This change allows runtime to use fibers or threads and do something useful, while the operation is in progress.

[cols="9,5,19"]
|===
| Platform           | Ruby ABI | File
| Checksums          |          | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0.sha256sum[couchbase-3.1.0.sha256sum]
| Source Archive     |          | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0.gem[couchbase-3.1.0.gem]
| Linux x86_64       | 3.0.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-linux-3.0.0.gem[couchbase-3.1.0-x86_64-linux-3.0.0.gem]
| Linux x86_64       | 2.7.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-linux-2.7.0.gem[couchbase-3.1.0-x86_64-linux-2.7.0.gem]
| Linux x86_64       | 2.6.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-linux-2.6.0.gem[couchbase-3.1.0-x86_64-linux-2.6.0.gem]
| Linux x86_64       | 2.5.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-linux-2.5.0.gem[couchbase-3.1.0-x86_64-linux-2.5.0.gem]
| macOS 10.15 x84_64 | 3.0.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-19-3.0.0.gem[couchbase-3.1.0-x86_64-darwin-19-3.0.0.gem]
| macOS 10.15 x84_64 | 2.7.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-19-2.7.0.gem[couchbase-3.1.0-x86_64-darwin-19-2.7.0.gem]
| macOS 10.15 x84_64 | 2.6.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-19-2.6.0.gem[couchbase-3.1.0-x86_64-darwin-19-2.6.0.gem]
| macOS 10.15 x84_64 | 2.5.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-19-2.5.0.gem[couchbase-3.1.0-x86_64-darwin-19-2.5.0.gem]
| macOS 10.13 x84_64 | 3.0.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-17-3.0.0.gem[couchbase-3.1.0-x86_64-darwin-17-3.0.0.gem]
| macOS 10.13 x84_64 | 2.7.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-17-2.7.0.gem[couchbase-3.1.0-x86_64-darwin-17-2.7.0.gem]
| macOS 10.13 x84_64 | 2.6.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-17-2.6.0.gem[couchbase-3.1.0-x86_64-darwin-17-2.6.0.gem]
| macOS 10.13 x84_64 | 2.5.0    | https://packages.couchbase.com/clients/ruby/sdk-3.1.0/couchbase-3.1.0-x86_64-darwin-17-2.5.0.gem[couchbase-3.1.0-x86_64-darwin-17-2.5.0.gem]
|===


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
