= Documents
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::{version-common}@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,ruby]
----
collection.upsert(docid, document)
collection.insert(docid, document)
collection.replace(docid, document)
collection.get(docid)
collection.remove(docid)
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,ruby]
----
include::example$documents.rb[tag=mutate-in]
----

or xref:7.1@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
UPDATE `travel-sample`.inventory.airline SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::{version-common}@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport USE KEYS ["airport_1254"];
----

or

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport WHERE META().id = "airport_1254";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by
specifying one or more sections of the document to be retrieved

[source,ruby]
----
include::example$documents.rb[tag=lookup-in]
----

The same behaviour could be achieved by using get with projections:

[source,ruby]
----
include::example$documents.rb[tag=lookup-in-projections]
----

// Counters

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters1]

[source,ruby]
----
include::example$documents.rb[tag=counters]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters2]

[source,ruby]
----
include::example$documents.rb[tag=counters-increment]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collection.binary()`.
This enables you to work with counters using `get()` and `replace()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase/BinaryCollection.html[in the API docs].

// Expiry
include::{version-common}@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::{version-common}@sdk:shared:partial$documents.adoc[tag=]


include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]
////
