= Couchbase Ruby SDK 3.2
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase Ruby SDK allows you to connect to a Couchbase cluster from Ruby. The Ruby SDK includes high-performance native Ruby extensions to handle communicating to the cluster over Couchbase’s binary protocols.


[.column]
[.content]
[source,ruby]
----
puts "\n==== Beer by strength (out of #{res.facets['by_strength'].total}):"
res.facets["by_strength"].numeric_ranges.each_with_index do |range, idx|
  puts "#{idx}. #{range.name}, ABV: [#{range.min}..#{range.max}] (#{range.count} records)"
end
----


++++
</div>
++++

[.column]
====== {empty}

== Couchbase Ruby SDK 3.2

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
Try out our xref:sample-application.adoc[Travel Sample Application].
And take a look at the xref:howtos:working-with-collections.adoc[Collections feature].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)]; 
xref:howtos:n1ql-queries-with-sdk.adoc[Query]; 
xref:howtos:full-text-searching-with-sdk.adoc[Search]; 
xref:howtos:analytics-using-sdk.adoc[Analytics]; 
xref:howtos:view-queries-with-sdk.adoc[Views] -- 
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase.html[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
The Couchbase Ruby SDK 3.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 & 6.6 as a xref:concept-docs:collections.adoc[developer preview]), and in xref:7.0@server:introduction:whats-new.adoc#whats-new-server-700[Couchbase 7.0].

[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to 
xref:project-docs:compatibility.adoc[compatibility tables]; 
xref:project-docs:sdk-release-notes.adoc[release notes]; and the 
xref:project-docs:get-involved.adoc[contribution guide]. 


[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/ruby-sdk/9[Couchbase forums^].
The Ruby SDK can be combined with many other projects in the broader Ruby ecosystem and beyond.

++++
</div>
++++
