= Sample Application
:description: Discover how to program interactions with the Couchbase Server via the Data, Query, and Search services -- using the Travel Sample Application with the built-in Travel Sample data Bucket.
:nav-title: Travel Sample App
:content-type: tutorial
:page-topic-type: tutorial
:page-aliases: ROOT:sample-application,ROOT:tutorial4,ROOT:sample-app-backend
:travel-sample-entrypoint: travel.rb
:travel-sample-git-project: try-cb-ruby
:page-pagination: prev

include::project-docs:partial$attributes.adoc[]

include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=abstract]

include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=quick-start]

include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=bring-your-own]

include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=using]

== Sample App Backend

The backend code shows Couchbase Ruby SDK in action with Query and Search,
but also how to plug together all of the elements and build an application with Couchbase Server and the Ruby SDK.

Here's the airport search code, which checks to see whether the search term for the query string is a three or four letter FAA or ICAO abbreviation,
and if not searches for it as an airport name:

[source,ruby,indent=0]
----
def get_airports(search_param)
  query_type = 'N1QL query - scoped to inventory: '

  query_prep = 'SELECT airportname FROM `travel-sample`.inventory.airport WHERE '

  same_case = search_param == search_param.downcase || search_param == search_param.upcase
  if same_case && search_param.length == 3
    query_prep += "faa=?"
    query_args = [search_param.upcase]
  elsif same_case && search_param.length == 4
    query_prep += "icao=?"
    query_args = [search_param.upcase]
  else
    query_prep += "POSITION(LOWER(airportname), ?) = 0"
    query_args = [search_param.downcase]
  end

  airport_list = []
  options = Cluster::QueryOptions.new
  options.positional_parameters(query_args)

  res = @cluster.query(query_prep, options)
  res.rows.each do |row|
    airport_list.push('airportname' => row['airportname'])
  end

  { 'context' => ["#{query_type} #{query_prep}"], 'data' => airport_list }
end
----

The https://github.com/couchbaselabs/{travel-sample-git-project}/blob/HEAD/{travel-sample-entrypoint}[{travel-sample-entrypoint}] file also contains the functions for handling users, registration, and {sqlpp} queries.


include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=data-model]

// TODO: Add this in when we have a swagger endpoint for Ruby
//include::{version-common}@sdk:shared:partial$sample-application.adoc[tag=rest-api]


// TODO: we don't use the partial here, because of the location of swagger.json
// in try-cb-dotnet/wwwroot/
== REST API

You can explore the REST API here in read-only mode, or once you are running the application, at the `/apidocs` endpoint.

// swagger_ui::https://raw.githubusercontent.com/couchbaselabs/{travel-sample-git-project}/HEAD/try-cb-dotnet/wwwroot/swagger.json[]

swagger_ui::https://raw.githubusercontent.com/couchbaselabs/try-cb-ruby/7.0/swagger.json[]
