= Install and Start Using the Ruby SDK with Couchbase Server
:description: The Couchbase Ruby SDK allows you to connect to a Couchbase cluster from Ruby.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
{description}
The Ruby SDK includes high-performance native Ruby extensions to handle communicating to the cluster over Couchbase’s binary protocols.

The Couchbase Ruby SDK 3.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area,
and adding support for future Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available in Couchbase Server 7.0).

Ruby SDK supports MRI Ruby versions 2.5, 2.6, and 2.7.

// tag::install[]

== Installing the SDK

The source package is available through https://rubygems.org/gems/couchbase and can be installed with

[source,console]
----
gem install couchbase
----

In addition to rubygems.org, we also maintain official gem repositories, where we publish not only source version of the package, but also precompiled binaries for Linux and MacOS.
Further details can be found on the xref:project-docs:sdk-release-notes.adoc[Release Notes & Archives page].
// end::install[]


== Hello Couchbase

Couchbase uses xref:7.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


// imports
[source,ruby]
----
include::example$start_using.rb[tag=imports,indent=0]
----

// initialize cluster
[source,ruby]
----
include::example$start_using.rb[tag=connect,indent=0]
----

The `Cluster` provides access to cluster-level operations like N1Ql queries, analytics, or full-text search.
You will also find different management APIs on it.
If you're developing client code on the same VM or machine as the Couchbase Server, your connection string can be just `localhost`.

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

Couchbase uses xref:7.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For production client code, you will want to use more appropriate, restrictive settings
 -- but here we want to get you up and running quickly,
so you can use the _Full Admin_ role created during installation of the Couchbase Data Platform, in which case set _Administrator_ as the username, and use the password that you defined in setting up your test Couchbase cluster.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,ruby]
----
include::example$start_using.rb[tag=bucket,indent=0]
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket_name_.

[source,ruby]
----
include::example$start_using.rb[tag=collection,indent=0]
----

The 3.2 SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature in the latest release of the Couchbase Data Platform, Couchbase Server 7.0.
This brings complete support for Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.


[source,ruby]
----
include::example$start_using.rb[tag=upsert-get,indent=0]
----

The code shows how you would use a named collection and scope. A named or default collection will provide the same functionality as bucket-level operations did in previous versions of Couchbase Server.

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.
// -- or first see a complete worked example of using the Couchbase php client, our xref:hello-world:sample-application.adoc[Travel Sample Application].

You can also perform a N1QL query at the cluster level:

[source,ruby]
----
include::example$start_using.rb[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].
Other services (like analytics, search or views) work very similar to the two shown above.
Please refer to their respective documentation sections to learn more.

After completing operations, finish with (otherwise resources will be released by garbage collector):

[source,ruby]
----
include::example$start_using.rb[tag=disconnect,indent=0]
----


== Cloud Connections

For developing on https://docs.couchbase.com/cloud/index.html[Couchbase Capella], if you are not working from the same _Availability Zone_ as your Capella instance, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments],
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements],
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and can be found https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase.html[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

Couchbase welcomes community contributions to the Ruby SDK.
The Ruby SDK source code is available on https://github.com/couchbase/couchbase-ruby-client[GitHub].
