= Install and Start Using the Ruby SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase Ruby SDK allows you to connect to a Couchbase cluster from Ruby.
The Couchbase Ruby SDK is a native Ruby extension and uses the Couchbase high-performance C library to handle communicating to the cluster over Couchbase binary protocols.


The Couchbase Ruby SDK 3.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).

The Couchbase Ruby SDK is compatible with Ruby 2.6 and 2.7.

// tag::install[]

== Installing the SDK

Before installing the Ruby SDK, you must install the xref:3.0@c-sdk:hello-world:start-using-sdk.adoc[C SDK -- _libcouchbase_ (LCB)];
version 3.0 or higher is required from Ruby Client 3.0.

After installing the C SDK, install the Ruby SDK through????:

[source,bash]
----
gem install --pre couchbase
----

Further details can be found on the xref:project-docs:sdk-release-notes.adoc[Release Notes & Archives page].

// installation and post-installation across platforms

// end::install[]

== Hello Couchbase

Couchbase uses xref:6.5@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


// initialize cluster

[source,ruby]
----
require 'couchbase'
include Couchbase

options = Cluster::ClusterOptions.new
options.authenticate("username", "password")
cluster = Cluster.connect("couchbase://10.143.201.101", options)
----

The `Cluster` provides access to cluster-level operations like N1Ql queries, analytics, or full-text search.
You will also find different management APIs on it.
If you're developing client code on the same VM or machine as the Couchbase Server, your connection string can be just `localhost`.

Couchbase uses xref:6.5@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For production client code, you will want to use more appropriate, restrictive settings
 -- but here we want to get you up and running quickly, 
so you can use the _Full Admin_ role created during installation of the Couchbase Data Platform, in which case set _Administrator_ as the username, and use the password that you defined in setting up your test Couchbase cluster.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,ruby]
----
bucket = cluster.bucket("test1")
----

// If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,ruby]
----
// get a collection reference
collection = bucket.default_collection

// or for named collection
collection = bucket.my-collection
----

The 3.0 SDK is ready for the introduction of xref:6.5@server:developer-preview:collections/collections-overview.adoc[Collections] in an upcoming release of the Couchbase Data Platform.
Couchbase Server 6.5 brings a limited xref:6.5@server:developer-preview:preview-mode.adoc[Developer Preview] of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Collection_. 
Here we've used the `DefaultCollection`, which provides the same functionality as bucket-level operations did in previous versions of Couchbase Server.

[source,ruby]
----
// upsert document
res = collection.upsert("u:king_arthur", {'name': 'Arthur', 'email': 'kingarthur@couchbase.com', 'interests': ['Holy Grails', 'African Swallows']})
p res.cas

// get document
res = collection.get("u:king_arthur")
p res.content
p res.cas
----

After completing operations, finish with:

[source,ruby]
----
cluster.disconnect
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.
// -- or first see a complete worked example of using the Couchbase php client, our xref:hello-world:sample-application.adoc[Travel Sample Application].

== Additional Resources

// The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-ruby-client-3.0.0/[here].
// Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

Couchbase welcomes community contributions to the Ruby SDK.
The Ruby SDK source code is available on https://github.com/couchbase/ruby-couchbase[GitHub].
