= Install and Start Using the Ruby SDK with Couchbase Server
:description: Installing the Couchbase Ruby SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
The Couchbase Ruby SDK allows you to connect to a Couchbase cluster from Ruby.
The Ruby SDK includes high-performance native Ruby extensions to handle communicating to the cluster over Couchbase’s binary protocols.

Ruby SDK supports https://www.ruby-lang.org/en/downloads/branches/[currently maintained Ruby versions], and recommends the latest stable version where possible (currently 3.1 as of May 2022.)


== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Ruby  SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password -- and see the <<cloud-connections, Cloud section>>, below.

[source,ruby]
----
include::hello-world:example$cloud.rb[tags=**]
----

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+ 
-- 
[source,ruby]
----
include::hello-world:example$start_using.rb[tags=**]
----

As well as the Ruby SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

== Quick Installation

A more detailed guide in our xref:project-docs:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

// tag::install[]

The source package is available through https://rubygems.org/gems/couchbase and can be installed with

[source,console]
----
gem install couchbase
----

In addition to rubygems.org, we also maintain official gem repositories, where we publish not only source version of the package, but also precompiled binaries for Linux and MacOS.
Further details can be found on the xref:project-docs:sdk-full-installation.adoc[Installation page].
// end::install[]


== Step-by-step

Start a new project (in VS Code or RubyMine, etc.) and create a file `cb-test.rb`.

// Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working with Ruby -- e.g. you are evaluating the Ruby SDK, but it is not your normal platform.

=== Prerequisites

Install the latest SDK package -- see <<quick-install,above>>.

The following code samples assume:

* Couchbase xref:cloud:ROOT:index.adoc[Capella] cluster, or Couchbase Server is installed and accessible locally (xref:server:getting-started:do-a-quick-install.adoc[Do a Quick Install] if you don't already have Couchbase Server installed).

* You have create a bucket (perhaps using the xref:server:manage:manage-settings/install-sample-buckets.adoc[travel-sample dataset], or by creating a new bucket).
Note, the Travel Sample bucket is installed automatically by the Capella free trial

* You have created a Couchbase user named "username" [change as appropriate] with permissions to access the cluster (at least Application Access permissions).

NOTE: Couchbase uses xref:server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


Firstly, you will need to have a few `import` statements at the top of your Ruby program:

[source,ruby]
----
include::example$start_using.rb[tag=imports,indent=0]
----


=== Connection

Then you can connect to the cluster:

[{tabs}] 
====
Capella Connection::
+
--
[source,csharp]
----
include::example$cloud.rb[tag=connect,indent=0]
----

From 3.3, the Ruby SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases:` in the Connection String as in this example.
--
Local Server Connection::
+
--
[source,ruby]
----
include::example$start_using.rb[tag=connect,indent=0]
----

For developing locally on the same machine as the Couchbase Server, your URI can be _couchbase://localhost_ as here. But for Production deployments, you will want to use a secure server,
with `couchbases://`.
--
====

The `Cluster` provides access to cluster-level operations like N1Ql queries, analytics, or full-text search.
You will also find different management APIs on it.
If you're developing client code on the same VM or machine as the Couchbase Server, your connection string can be just `localhost`.

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

Couchbase uses xref:7.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For production client code, you will want to use more appropriate, restrictive settings
-- but here we want to get you up and running quickly,
so you can use the _Full Admin_ role created during installation of the Couchbase Data Platform, in which case set _Administrator_ as the username, and use the password that you defined in setting up your test Couchbase cluster.


=== Bucket, Scopes, and Collections

Open the bucket:
[source,ruby]
----
include::example$start_using.rb[tag=bucket,indent=0]
----


Collections allow Documents to be grouped by purpose or theme, according to specified _Scope_.
Our Travel Sample bucket has separate scopes for inventory (flights, etc.), and for tenants (different travel agents).

[source,ruby]
----
include::example$start_using.rb[tag=collection,indent=0]
----

To get you started the following code creates a new document in a custom scope and collection and then fetches it again, printing the result.


[source,ruby]
----
include::example$start_using.rb[tag=upsert-get,indent=0]
----

[NOTE]
====
Other possible key/value CRUD Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
====

You can also perform a N1QL query with the cluster object:

[source,rb]
----
include::example$start_using.rb[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].

After completing operations, finish with (otherwise resources will be released by garbage collector):

[source,ruby]
----
include::example$start_using.rb[tag=disconnect,indent=0]
----


== Cloud Connections

For developing on https://docs.couchbase.com/cloud/index.html[Couchbase Capella], if you are not working from the same _Availability Zone_ as your Capella instance, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments],
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements],
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and can be found https://docs.couchbase.com/sdk-api/couchbase-ruby-client/Couchbase.html[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

Couchbase welcomes community contributions to the Ruby SDK.
The Ruby SDK source code is available on https://github.com/couchbase/couchbase-ruby-client[GitHub].


=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/ruby-sdk/9[community forum] is a great source of help.
